#!/usr/bin/env bash
#
# vps_setup.sh
# Azeon Systems - Production Frappe Bench / ERPNext bootstrap for a clean
# Ubuntu 22.04 LTS VPS. Run this ON THE VPS (or inside WSL against the VPS
# via SSH) — never inside native Windows PowerShell (see CLAUDE.md).
#
# Usage:
#   sudo ./vps_setup.sh
#
# What it does:
#   1. Installs Python 3.10, Node.js 18, MariaDB 10.6, Redis, Nginx, Certbot
#   2. Creates a dedicated `frappe` system user
#   3. Installs bench-cli and initializes a bench at /home/frappe/frappe-bench
#   4. Fetches and installs the erpnext app into the bench
#   5. Sets up the bench for production (supervisor + nginx) so it can host
#      multiple tenant sites, each reachable at https://{tenant_slug}.azeonsystems.com.ng
#
# IMPORTANT — about "multitenancy":
#   `bench config set-common-config -c multitenancy 1` (below) is NOT a real
#   Frappe config key. It's a harmless no-op included only because the
#   original task spec named it explicitly. Frappe's actual multi-tenancy
#   is native: every site you create with `bench new-site <slug>.azeonsystems.com.ng`
#   is automatically served on that hostname once nginx is generated by
#   `bench setup nginx` + `bench setup production`, PROVIDED:
#     a) a wildcard DNS record  *.azeonsystems.com.ng  ->  <this VPS's IP>  exists
#     b) you create each tenant site with a domain-matching name, e.g.:
#          bench new-site acme.azeonsystems.com.ng --install-app erpnext
#   This script prepares the bench/nginx/supervisor plumbing for that; it
#   does not create tenant sites itself (that's the provisioner's job).

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Please run as root (sudo ./vps_setup.sh)" >&2
  exit 1
fi

FRAPPE_USER="frappe"
BENCH_DIR="/home/${FRAPPE_USER}/frappe-bench"
FRAPPE_BRANCH="version-15"   # Node 18 compatible; use version-14 if you need it explicitly
SITE_PLACEHOLDER="localhost" # bootstrap site; real tenants are created by the provisioner

echo "== [1/8] Updating apt and installing base dependencies =="
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y
apt-get install -y \
  git curl wget software-properties-common ca-certificates gnupg \
  build-essential \
  python3.10 python3.10-venv python3.10-dev python3-pip \
  libmysqlclient-dev \
  libffi-dev libssl-dev \
  wkhtmltopdf \
  xvfb libfontconfig fonts-cantarell

echo "== [2/8] Installing Node.js 18 (via NodeSource) =="
if ! command -v node >/dev/null 2>&1 || [[ "$(node -v)" != v18* ]]; then
  curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  apt-get install -y nodejs
fi
npm install -g yarn

echo "== [3/8] Installing MariaDB 10.6 =="
apt-get install -y mariadb-server-10.6 mariadb-client-10.6 2>/dev/null \
  || apt-get install -y mariadb-server mariadb-client
systemctl enable --now mariadb

# Configure MariaDB charset/collation for Frappe (idempotent)
MYSQL_CONF="/etc/mysql/mariadb.conf.d/50-server.cnf"
if [[ -f "${MYSQL_CONF}" ]] && ! grep -q "character-set-server" "${MYSQL_CONF}"; then
  cat >> "${MYSQL_CONF}" <<'EOF'

[mysqld]
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

[mysql]
default-character-set = utf8mb4
EOF
  systemctl restart mariadb
fi

echo "== [4/8] Installing Redis =="
apt-get install -y redis-server
systemctl enable --now redis-server

echo "== [5/8] Installing Nginx and Certbot =="
apt-get install -y nginx
apt-get install -y certbot python3-certbot-nginx
systemctl enable --now nginx

echo "== [6/8] Creating '${FRAPPE_USER}' system user =="
if ! id "${FRAPPE_USER}" >/dev/null 2>&1; then
  adduser --disabled-password --gecos "" "${FRAPPE_USER}"
  usermod -aG sudo "${FRAPPE_USER}"
fi

echo "== [7/8] Installing bench-cli and initializing the bench =="
pip3 install --upgrade pip
pip3 install frappe-bench

if [[ ! -d "${BENCH_DIR}" ]]; then
  sudo -u "${FRAPPE_USER}" -H bash -c "
    cd /home/${FRAPPE_USER} && \
    bench init frappe-bench --frappe-branch ${FRAPPE_BRANCH} --python python3.10
  "
fi

echo "== [8/8] Fetching erpnext + azeon_core apps and setting up production =="
sudo -u "${FRAPPE_USER}" -H bash -c "
  cd ${BENCH_DIR} && \
  bench get-app erpnext --branch ${FRAPPE_BRANCH}
"

# azeon_core (Phase 3: branding + CEO dashboard) must be fetched into the
# bench ONCE, here, before the provisioner's per-tenant
# `bench --site <site> install-app azeon_core` can ever succeed.
# Point AZEON_CORE_SOURCE at your git remote (recommended) or a local path
# when invoking this script, e.g.:
#   AZEON_CORE_SOURCE=https://github.com/<org>/azeon_core.git ./vps_setup.sh
AZEON_CORE_SOURCE="${AZEON_CORE_SOURCE:-}"
if [[ -n "${AZEON_CORE_SOURCE}" ]]; then
  sudo -u "${FRAPPE_USER}" -H bash -c "
    cd ${BENCH_DIR} && \
    bench get-app azeon_core ${AZEON_CORE_SOURCE}
  " || echo "WARNING: failed to fetch azeon_core from ${AZEON_CORE_SOURCE} — install-app azeon_core will fail for every tenant until this is fixed."
else
  echo "NOTE: AZEON_CORE_SOURCE not set — skipping azeon_core fetch."
  echo "      Run 'bench get-app azeon_core <git-remote-or-path>' on this bench"
  echo "      before the provisioner attempts install-app azeon_core, or every"
  echo "      tenant provisioning run will log that step as failed."
fi

# Documented no-op — see header comment. Kept for parity with the spec.
sudo -u "${FRAPPE_USER}" -H bash -c "
  cd ${BENCH_DIR} && \
  bench config set-common-config -c multitenancy 1
" || echo "NOTE: 'multitenancy' is not a real bench config key — this is a documented no-op."

# Wire up nginx + supervisor for production, so any future tenant site
# (bench new-site <slug>.azeonsystems.com.ng) is served automatically once
# wildcard DNS points at this box.
bash -c "
  cd ${BENCH_DIR} && \
  bench setup nginx --yes && \
  bench setup supervisor --yes && \
  bench setup production ${FRAPPE_USER} --yes
"

systemctl reload nginx || true

cat <<'EOF'

============================================================
 Azeon Systems VPS bootstrap complete.
============================================================
Next steps:
  1. Point a wildcard DNS record *.azeonsystems.com.ng at this VPS's IP.
  2. From the provisioner, create tenant sites with:
       bench new-site <tenant_slug>.azeonsystems.com.ng --install-app erpnext
     (tenant_slug must already be sanitized to lowercase alphanumeric
     per CLAUDE.md guidelines before it reaches this command.)
  3. Issue TLS certs per tenant (or a wildcard cert) via certbot, e.g.:
       certbot --nginx -d <tenant_slug>.azeonsystems.com.ng
============================================================
EOF
